name: CI

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup DotNet 9.0 Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0

      - name: dotnet test
        run: dotnet test --configuration Release

      - name: dotnet publish
        run: dotnet publish WeatherApplication/WeatherApplication.csproj --configuration Release -o artifacts

      - uses: actions/upload-artifact@v4
        with:
          name: dometrain-artifact
          path: artifacts/


  deploy_dev:
  
    name: Deploy Dev
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dometrain-artifact
          path: artifacts/

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deploy to Azure App Service'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: app-dometrain-github-actions # Replace with your app name
          package: artifacts/