name: PR Verify

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: PR Verify
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup DotNet 9.0 Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet test
        run: dotnet test --configuration Release --no-build

      - name: dotnet format
        run: dotnet format -v detailed --verify-no-changes