name: PR Verify

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: PR Verify
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup DotNet 8.0.11 Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.11

      - name: Build with dotnet
        run: dotnet build --configuration Release

