name: PR Verify

on:
  workflow_dispatch:

jobs:
  secrets:
    name: Secrets Demo
    runs-on: ubuntu-latest

    steps:
      - name: dotnet format
        run: dotnet format -v detailed --verify-no-changes