name: Secrets

on:
  pull_request:
    branches: ["main"]

env:
  API_CSPROJ_PATH: "./WeatherApplication/WeatherApplication.csproj"

jobs:
  secrets:
    name: Secrets Demo
    runs-on: ubuntu-latest

    steps:
      - name: echo environment variable
        run: echo "The value of ${{ secrets.SECRET_API_KEY }} is $API_CSPROJ_PATH"
